-- Create webhook_audit_log table for storing all request/response audit data
create table webhook_audit_log (
    id bigint generated by default as identity not null,
    request_method text not null,
    request_path text not null,
    request_headers jsonb,
    request_body jsonb,
    response_status integer not null,
    response_body jsonb,
    received_at timestamp with time zone not null default now(),
    constraint webhook_audit_log_pkey primary key (id)
) TABLESPACE pg_default;

-- Add indexes for common query patterns
create index IF not exists idx_webhook_audit_log_received_at on public.webhook_audit_log using btree (received_at desc) TABLESPACE pg_default;
create index IF not exists idx_webhook_audit_log_request_method on public.webhook_audit_log using btree (request_method) TABLESPACE pg_default;
create index IF not exists idx_webhook_audit_log_response_status on public.webhook_audit_log using btree (response_status) TABLESPACE pg_default;